- name: Create Kubernetes configuration directory
  file: path=/etc/kubernetes state=directory

- name: Install Kubernetes config conf
  template: src=config.j2
            dest=/etc/kubernetes/config
            owner=root
            group=root
            mode=0644
